// Date: 15/10/2019 16:44:21
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

public static class ModelNew extends ModelBase {
	// fields
	ModelRenderer BookSide1;
	ModelRenderer BookSide2;
	ModelRenderer BookPage1;
	ModelRenderer BookPage2;

	public ModelNew() {
		textureWidth = 64;
		textureHeight = 32;

		BookSide1 = new ModelRenderer(this, 0, 0);
		BookSide1.addBox(0F, 0F, 0F, 5, 7, 2);
		BookSide1.setRotationPoint(2.3F, 0F, 1.7F);
		BookSide1.setTextureSize(64, 32);
		BookSide1.mirror = true;
		setRotation(BookSide1, 0F, 0.3607014F, 0F);
		BookSide2 = new ModelRenderer(this, 16, 0);
		BookSide2.addBox(0F, 0F, 0F, 5, 7, 2);
		BookSide2.setRotationPoint(-2F, 0F, 0F);
		BookSide2.setTextureSize(64, 32);
		BookSide2.mirror = true;
		setRotation(BookSide2, 0F, -0.3490659F, 0F);
		BookPage1 = new ModelRenderer(this, 0, 11);
		BookPage1.addBox(0F, 0F, 0F, 4, 6, 1);
		BookPage1.setRotationPoint(-1.4F, 0.3F, -1F);
		BookPage1.setTextureSize(64, 32);
		BookPage1.mirror = true;
		setRotation(BookPage1, 0F, -0.3717861F, 0F);
		BookPage2 = new ModelRenderer(this, 14, 11);
		BookPage2.addBox(0F, 0F, 0F, 4, 6, 1);
		BookPage2.setRotationPoint(2.7F, 0.4F, 0.7F);
		BookPage2.setTextureSize(64, 32);
		BookPage2.mirror = true;
		setRotation(BookPage2, 0F, 0.3346075F, 0F);
	}

	public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
		super.render(entity, f, f1, f2, f3, f4, f5);
		setRotationAngles(f, f1, f2, f3, f4, f5, entity);
		BookSide1.render(f5);
		BookSide2.render(f5);
		BookPage1.render(f5);
		BookPage2.render(f5);
	}

	private void setRotation(ModelRenderer model, float x, float y, float z) {
		model.rotateAngleX = x;
		model.rotateAngleY = y;
		model.rotateAngleZ = z;
	}

	public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity e) {
		super.setRotationAngles(f, f1, f2, f3, f4, f5, e);
		this.BookSide1.rotateAngleY = f2 / 20.f;
		this.BookSide2.rotateAngleY = f2;
		this.BookPage2.rotateAngleY = f2;
		this.BookPage1.rotateAngleY = f2;
	}

}
