// Date: 16/10/2019 06:39:29
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

public static class ModelEyeball extends ModelBase {
	// fields
	ModelRenderer Eyeball;
	ModelRenderer Wing1;
	ModelRenderer Wing2;

	public ModelEyeball() {
		textureWidth = 64;
		textureHeight = 32;

		Eyeball = new ModelRenderer(this, 0, 0);
		Eyeball.addBox(0F, 0F, 0F, 8, 8, 8);
		Eyeball.setRotationPoint(-3.533333F, -7F, -4F);
		Eyeball.setTextureSize(64, 32);
		Eyeball.mirror = true;
		setRotation(Eyeball, 0F, 0F, 0F);
		Wing1 = new ModelRenderer(this, 35, 0);
		Wing1.addBox(0F, 0F, 0F, 8, 1, 4);
		Wing1.setRotationPoint(3F, -8F, -2F);
		Wing1.setTextureSize(64, 32);
		Wing1.mirror = true;
		setRotation(Wing1, 0F, 0F, 0F);
		Wing2 = new ModelRenderer(this, 35, 0);
		Wing2.addBox(0F, 0F, 0F, 8, 1, 4);
		Wing2.setRotationPoint(-10F, -8F, -2F);
		Wing2.setTextureSize(64, 32);
		Wing2.mirror = true;
		setRotation(Wing2, 0F, 0F, 0F);
	}

	public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
		super.render(entity, f, f1, f2, f3, f4, f5);
		setRotationAngles(f, f1, f2, f3, f4, f5, entity);
		Eyeball.render(f5);
		Wing1.render(f5);
		Wing2.render(f5);
	}

	private void setRotation(ModelRenderer model, float x, float y, float z) {
		model.rotateAngleX = x;
		model.rotateAngleY = y;
		model.rotateAngleZ = z;
	}

	public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity e) {
		super.setRotationAngles(f, f1, f2, f3, f4, f5, e);
		this.Eyeball.rotateAngleY = f3 / (180F / (float) Math.PI);
		this.Eyeball.rotateAngleX = f4 / (180F / (float) Math.PI);
		this.Wing2.rotateAngleX = f2 / 20.f;
		this.Wing1.rotateAngleX = f2 / 20.f;
	}

}
