// Date: 15/10/2019 18:02:31
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

public static class ModelKnight extends ModelBase {
	// fields
	ModelRenderer head;
	ModelRenderer body;
	ModelRenderer rightarm;
	ModelRenderer leftarm;
	ModelRenderer rightleg;
	ModelRenderer leftleg;
	ModelRenderer Horn1;
	ModelRenderer Horn2;
	ModelRenderer HornTop1;
	ModelRenderer HornTop2;

	public ModelKnight() {
		textureWidth = 64;
		textureHeight = 32;

		head = new ModelRenderer(this, 0, 0);
		head.addBox(-4F, -8F, -4F, 8, 8, 8);
		head.setRotationPoint(0F, 0F, 0F);
		head.setTextureSize(64, 32);
		head.mirror = true;
		setRotation(head, 0F, 0F, 0F);
		body = new ModelRenderer(this, 16, 16);
		body.addBox(-4F, 0F, -2F, 8, 12, 4);
		body.setRotationPoint(0F, 0F, 0F);
		body.setTextureSize(64, 32);
		body.mirror = true;
		setRotation(body, 0F, 0F, 0F);
		rightarm = new ModelRenderer(this, 40, 16);
		rightarm.addBox(-3F, -2F, -2F, 4, 12, 4);
		rightarm.setRotationPoint(-5F, 2F, 0F);
		rightarm.setTextureSize(64, 32);
		rightarm.mirror = true;
		setRotation(rightarm, 0F, 0F, 0F);
		leftarm = new ModelRenderer(this, 40, 16);
		leftarm.addBox(-1F, -2F, -2F, 4, 12, 4);
		leftarm.setRotationPoint(5F, 2F, 0F);
		leftarm.setTextureSize(64, 32);
		leftarm.mirror = true;
		setRotation(leftarm, 0F, 0F, 0F);
		rightleg = new ModelRenderer(this, 0, 16);
		rightleg.addBox(-2F, 0F, -2F, 4, 12, 4);
		rightleg.setRotationPoint(-2F, 12F, 0F);
		rightleg.setTextureSize(64, 32);
		rightleg.mirror = true;
		setRotation(rightleg, 0F, 0F, 0F);
		leftleg = new ModelRenderer(this, 0, 16);
		leftleg.addBox(-2F, 0F, -2F, 4, 12, 4);
		leftleg.setRotationPoint(2F, 12F, 0F);
		leftleg.setTextureSize(64, 32);
		leftleg.mirror = true;
		setRotation(leftleg, 0F, 0F, 0F);
		Horn1 = new ModelRenderer(this, 35, 0);
		Horn1.addBox(0F, 0F, 0F, 3, 2, 2);
		Horn1.setRotationPoint(4F, -8F, -1F);
		Horn1.setTextureSize(64, 32);
		Horn1.mirror = true;
		setRotation(Horn1, 0F, 0F, 0F);
		Horn2 = new ModelRenderer(this, 35, 0);
		Horn2.addBox(0F, 0F, 0F, 3, 2, 2);
		Horn2.setRotationPoint(-7F, -8F, -1F);
		Horn2.setTextureSize(64, 32);
		Horn2.mirror = true;
		setRotation(Horn2, 0F, 0F, 0F);
		HornTop1 = new ModelRenderer(this, 35, 6);
		HornTop1.addBox(0F, 0F, 0F, 2, 3, 2);
		HornTop1.setRotationPoint(7F, -10F, -1F);
		HornTop1.setTextureSize(64, 32);
		HornTop1.mirror = true;
		setRotation(HornTop1, 0F, 0F, 0F);
		HornTop2 = new ModelRenderer(this, 35, 6);
		HornTop2.addBox(0F, 0F, 0F, 2, 3, 2);
		HornTop2.setRotationPoint(-9F, -10F, -1F);
		HornTop2.setTextureSize(64, 32);
		HornTop2.mirror = true;
		setRotation(HornTop2, 0F, 0F, 0F);
	}

	public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
		super.render(entity, f, f1, f2, f3, f4, f5);
		setRotationAngles(f, f1, f2, f3, f4, f5, entity);
		head.render(f5);
		body.render(f5);
		rightarm.render(f5);
		leftarm.render(f5);
		rightleg.render(f5);
		leftleg.render(f5);
		Horn1.render(f5);
		Horn2.render(f5);
		HornTop1.render(f5);
		HornTop2.render(f5);
	}

	private void setRotation(ModelRenderer model, float x, float y, float z) {
		model.rotateAngleX = x;
		model.rotateAngleY = y;
		model.rotateAngleZ = z;
	}

	public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity e) {
		super.setRotationAngles(f, f1, f2, f3, f4, f5, e);
		this.head.rotateAngleY = f3 / (180F / (float) Math.PI);
		this.head.rotateAngleX = f4 / (180F / (float) Math.PI);
		this.Horn1.rotateAngleY = f3 / (180F / (float) Math.PI);
		this.Horn1.rotateAngleX = f4 / (180F / (float) Math.PI);
		this.rightleg.rotateAngleX = MathHelper.cos(f * 1.0F) * 1.0F * f1;
		this.Horn2.rotateAngleY = f3 / (180F / (float) Math.PI);
		this.Horn2.rotateAngleX = f4 / (180F / (float) Math.PI);
		this.HornTop2.rotateAngleY = f3 / (180F / (float) Math.PI);
		this.HornTop2.rotateAngleX = f4 / (180F / (float) Math.PI);
		this.rightarm.rotateAngleX = MathHelper.cos(f * 0.6662F + (float) Math.PI) * f1;
		this.leftleg.rotateAngleX = MathHelper.cos(f * 1.0F) * -1.0F * f1;
		this.HornTop1.rotateAngleY = f3 / (180F / (float) Math.PI);
		this.HornTop1.rotateAngleX = f4 / (180F / (float) Math.PI);
		this.leftarm.rotateAngleX = MathHelper.cos(f * 0.6662F) * f1;
	}

}
